opt_einsum/__init__.py
setup.py

The code had a minor issue with python 3, mainly because of using `basestring` instead of `str`. This is fixed now so that the code runs on python 2.7 as well as python 3.5. 
I also did reformat some parts to make the code compatible to the PEP8 recommendations.

Making opt_einsum python 3 compatible

---

README.md
opt_einsum/__init__.py
opt_einsum/contract.py
tests/test_contract.py

This is a first run at ``contract_expression`` - for building reusable tensor contraction functions based solely on array shapes, which could then for example be cached for efficiency:
```python
>>> expr = contract_expression("ab,bc->ac", (3, 4), (4, 5))
>>> expr
<opt_einsum.contract.ContractExpression at 0x7f68f44801d0>
>>> a, b = np.random.rand(3, 4), np.random.rand(4, 5)
>>> c = expr(a, b)
>>> np.allclose(c, a @ b)
True
```
Closes #10 and might be a useful starting point for #7 (e.g. storing the constant args in the ``ContractExpression``).
Further thoughts
----
1. Semantics / name? The alternate einsum convention is possible but gets pretty unreadable: i.e. ``contract_expression((3, 4), (0, 1), (4, 5), (0, 1))``...
2. More checks? currently these are minimal (I've just tested to make …

contract_expression for reusable contractions

---

README.md
opt_einsum/contract.py
opt_einsum/helpers.py
opt_einsum/parser.py
opt_einsum/paths.py
tests/test_contract.py
tests/test_paths.py

This PR contains a couple of improvements for efficiently contracting large networks of tensors, e.g. MPS, PEPS, MERA.
1. Allow ~1000 unique indices to be used. This is only for python3, which uses unicode strings by default. The only trick here really is that calls (e.g. pairwise contractions) to np.einsum must have their string mapped into [a-z,A-Z] with a bit of care taken about ordering.
2. Improve the performance significantly when finding the greedy path for many tensors. This is partly from refactoring ``find_contraction``, which was a hot spot, but mainly from ignoring any potential outer products (which are never advantageous to perform eagerly) while potential inner products are remaining.
For example, finding a path for 200 tensors with ~300 unique indices takes < ~1sec. …

Improvements for large networks of tensors

---

.gitignore
README.md
docs/source/api.rst
docs/source/conf.py
docs/source/greedy_path.rst
docs/source/index.rst
docs/source/optimal_path.rst
docs/source/path_finding.rst
docs/source/reusing paths.rst
opt_einsum/contract.py
opt_einsum/paths.py
tests/test_paths.py

Updates to the docs:
------------
- Added reusing paths section
- Added autosummary references for the main functions (so they are clickable in the docs)
- fixed a few rst warnings.
I was wondering if it might be a good idea to strip down the README a bit and have it point to readthedocs so as not to duplicate info?
Greedy tweak
-----------
The tweak to greedy is to calculate ``removed_size`` as the ``size_tensors_removed - size_tensor_created``. This largely produces the same contractions but is occasionally better --- on the two tests I had to update ``greedy`` now produces the same scaling as ``optimal``.
As a quick example of when this works well, imagine this tensor contraction (as a diagram with larger indices along the top and bottom)::
A=A=A=A=A=A=A=A=A
| | | | | | | | | …

Update docs and tweak greedy

---

.codecov.yml

Going down in coverage by a marginal amount is ok with me during changes. I dislike the full enforcement so turning that off unless coverage drops below 80%.

Stop Codecov failures

---

.travis.yml
README.md
docs/requirements.yml
docs/source/backends.rst
docs/source/greedy_path.rst
docs/source/index.rst
opt_einsum/backends.py
opt_einsum/blas.py
opt_einsum/contract.py
opt_einsum/parser.py
opt_einsum/paths.py
readthedocs.yml
tests/test_backends.py
tests/test_blas.py
tests/test_contract.py

This adds non-numpy backend support to ``opt_einsum`` in two flavors: 
For arbitrary ndarray libraries, i.e. if the arrays supplied have got a ``.shape`` attribute and opt_einsum can find ``{backend}.tensordot`` etc then it should work, returning whatever type the library uses. So for example 
```python
contract("abc,bcd,def->aef", *dask_arrays, backend='dask')
```
will return a ``dask.Array`` without any explicit logic. I've added tests for [dask](https://github.com/dask/dask/issues/732) and also [sparse](https://github.com/pydata/sparse/issues/31).
Edit: I should add that extra functionality like taking diagonals etc is still reliant on a ``einsum`` implementation. Not sure about broadcasting status etc.
To support GPU operations on numpy arrays, here, on first call the arrays are …

non-numpy (e.g. GPU) backend support

---

opt_einsum/parser.py
tests/test_backends.py

Quick fix as I had forgotten to test the normal ``contract`` with backend - in its parsing it was converting all operands with ``np.asanyarray(x)``. It now only does this if the operand doesn't have a `shape` attribute.

fix raw contract with backend

---

docs/source/index.rst
paper/paper.bib
paper/paper.md

This PR starts a [JOSS](http://joss.theoj.org) article to publish this repo. I have added @jcmgray as a co-author due to the large number of changes made to the backend functionality. Any other contributor is more than welcome on the paper if they are willing to read over the draft and approve it.
For now, the paper mostly reproduces the docs intro. However, considering the generic nature of the journal we may need to spend a bit more time discussing what `einsum` and tensor contractions are.
I would also like to coincide this with another `opt_einsum` release, many changes have happened since the last one. Perhaps a 2.0 due to the many backend changes.
Closes #14.

JOSS article

---

docs/source/api.rst
docs/source/ex_large_expr_with_greedy.rst
docs/source/greedy_path.rst
opt_einsum/__init__.py
opt_einsum/helpers.py
opt_einsum/parser.py

Going over numpy/numpy#11345 I saw this line which would have become slow when all the new symbols were introduced. On my machine this new behaviour brings the time to find a simple contraction path with ellipses back down from about 80us to 35us.
This is not really necessary for the numpy code as it only has 52 symbols (are there plans to change that?).
Also with this change, the number of symbols used now should have no impact on performance, just memory, I was wondering about further increasing the number to several thousand?

Allow arbitrary indices + fix minor perf regression when using ellipses

---

README.md
opt_einsum/tests/test_contract.py

This PR documents and tests the fact that `opt_einsum.contract` is a drop in for `np.einsum`.

DOC: drop in replacement

---

docs/source/backends.rst
docs/source/reusing_paths.rst
opt_einsum/backends.py
opt_einsum/contract.py
opt_einsum/tests/test_backends.py
opt_einsum/tests/test_contract.py

This allows constant tensors to be supplied to ``contract_expression``, which will then build as many constant intermediaries as it can. Still a bit of a work in progress but the core functionality is working so thought I'd share. Resolves #7.
Basic setup:
```python
>>> from opt_einsum import contract_expression
>>> from numpy.random import rand
>>> equation = 'ij,jk,kl,lm,mn->ni'
>>> const_ops = rand(2, 2), rand(2, 2), rand(2, 2)
>>> ops = (3, 2), *const_ops, (2, 3)  # non-const ops are just shapes
>>> expr = contract_expression(equation, *ops, constants=[1, 2, 3])
>>> expr
ContractExpression('ij,mn,[jk,kl,lm]->ni')
>>> print(expr)
<ContractExpression> for 'ij,mn,[jk,kl,lm]->ni':
1.  'jm,ij->mi' [GEMM]
2.  'mi,mn->ni' [GEMM]
```
Now we can call it with just two arrays:
```python
>>> …
```

[WIP] allow constant tensors in expressions

---

.travis.yml
devtools/conda-envs/full_test.yaml
devtools/travis-ci/before_install.sh

Switches testing to `conda` as the backend install are increasingly more compilation dependent.
@jcmgray Do you have a conda caching example, historically this has given me quite a bit of trouble.

CI: Switches to conda for environment testing

---

opt_einsum/contract.py
opt_einsum/helpers.py
opt_einsum/paths.py
opt_einsum/tests/test_backends.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_input.py

* Enables 'auto' mode as the default contraction path. This uses the optimal path for 4 or less operators, but otherwise the greedy path - @dgasmith not sure if you were also about to add 'auto' mode (in which case I can remove).
* A few other tweaks that up the test coverage a bit.

'auto' path mode + test coverage

---

opt_einsum/backends/torch.py
opt_einsum/helpers.py
opt_einsum/parser.py
opt_einsum/tests/test_backends.py

This renames symbols to support PyTorch 0.4.1 which supports only symbols a-z. This is useful when the overall computation has more than 26 dimensions but any single contraction requires only 26 or fewer dimensions.
- Added a test with non-lowercase symbols
- Tested that this works in an application using Pyro https://github.com/uber/pyro/pull/1313

Rename symbols to support torch.einsum

---

README.md
setup.py

This attempts to fix an error reported by @martinjankowiak when pip installing `opt_einsum` in Python 3.6:
```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-09n_lk1q/opt-einsum/setup.py", line 7, in <module>
long_description = handle.read()
File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3749: ordinal not in range(128)
```
I haven't been able to reproduce the error, but it appears to be due to failure to parse the letter μ. I've
1. replace 'μ' with 'u', and
2. embedded the `long_description` parsing in a try-except to avoid …

Avoid unicode in README.md; avoid failing in setup.py

---

opt_einsum/compat.py
opt_einsum/contract.py
opt_einsum/parser.py
opt_einsum/sharing.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_input.py
opt_einsum/tests/test_paths.py

Fixes #42
This provides a compatibility shim for Python 2 so that `get_symbol(n)` can work for larger n.
Note that Python 2's `numpy.einsum` still does not accept unicode. This means that, while `opt_einsum` can now work with arbitrarily large contractions in Python 2, it only works with contractions whose individual calls to Numpy involve fewer than 52 (I believe) characters.

Make get_symbol(large_number) work in Python2

---

opt_einsum/sharing.py
opt_einsum/tests/test_sharing.py

Makes ``shared_intermediates`` thread safe, by storing the caches in a dict referenced by thread id. All threads can (still) share the same cache among themselves, if it is supplied to them all. Resolves #51. cc @fritzo.

make shared_intermediates thread-safe

---

docs/source/greedy_path.rst
opt_einsum/contract.py
opt_einsum/helpers.py
opt_einsum/parser.py
opt_einsum/tests/test_backends.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_paths.py
scripts/compare_random_paths.py

In the process of comparing/benchmarking the new 'cheap' path (#60) I thought various consistency/convenience updates to the path machinery might be worthwhile. Some of these are bigger than others so definitely let me know what you think. 
1. Per #55, change the ``memory_limit`` default to unlimited. As I mentioned in the other thread, I think any time that the arrays are going to get too big for RAM, resorting to einsum is going to be so exponentially slow that a ``MemoryError`` might be preferable. We could add ``'warn'/'system'`` versions that take system memory into account, the only thing is that this requires checking the output dtype and getting the systems free memory which is a bit of overhead. This change does make 'optimal' a bit slower, but at the same time, it possibly …

various changes to path machinery

---

docs/source/api.rst
docs/source/eager_path.rst
docs/source/index.rst
opt_einsum/contract.py
opt_einsum/paths.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_paths.py

Addresses #56 
Mirrors ~~https://github.com/uber/pyro/pull/1424~~ https://github.com/uber/pyro/pull/1430
Implements a cheap approximate optimizer for very large paths. This is currently over 100x faster on some large contractions in Pyro, but produces slightly suboptimal paths.
- ~~Add quality tests (will be easier after #61)~~

Add prototype cheap optimizer

---

opt_einsum/backends/torch.py

This just makes ``torch`` use ``tensordot`` if it has it (it was implemented [recently here](https://github.com/pytorch/pytorch/pull/10025)), rather than the ``einsum`` based workaround. Haven't noticed much of a performance difference, but probably best practice.

torch backend: use tensordot if available

---

docs/source/index.rst
docs/source/input_format.rst
opt_einsum/parser.py
opt_einsum/tests/test_input.py

* Add more symbol support based on hash
* Refactor the converting to subscripts routine a little bit
* Update tests
Make opt_einsum support anything hashable as subscripts, such as:
```python
contract(arr1, ['left edge', 'bond'], arr2, ['bond', 'right edge'])
```
See #67

Support more symbols for subscripts (#67)

---

docs/source/index.rst
docs/source/input_format.rst
opt_einsum/contract.py
opt_einsum/parser.py
opt_einsum/tests/test_contract.py

Makes ``contract_expression`` accept interleaved-style input (fixes #71) and adds general documentation on the input formats (resolves #70) following on from #67.

input fixes and docs

---

opt_einsum/backends/dispatch.py
opt_einsum/contract.py

This PR makes backends fully overridable by checking each backed for a transpose function before using the default `.transpose()` method.
Before this PR, `_transpose()` would first look for a default implementation (`x.transpose(axes)`), and only if this failed look for an overridden backend `transpose()` function. This approach has two flaws: (1) backends cannot override the transpose function if a different `.transpose()` method already exists (e.g. in Pyro we want to track some metadata in `transpose()`); (2) the try-except may not play well with jit compilers like the PyTorch jit.
The only change in behavior is to the torch backend: before this PR `torch.transpose()` was used for transposes of 2 axes and `torch.permute()` was used for 3 or more axes; after this PR `torch.permute()` is …

Allow overriding of transpose function

---

opt_einsum/contract.py

This fixes path optimizers to work when run under the PyTorch jit. The problem was that when running under the jit, `x.shape` is a tensor, and `x.shape[pos]` is also a tensor. These tensors can't be operated on as easily as ints. this PR merely casts to an `int`. Note this will still raise a warning in the PyTorch jit, but it is easy to filter out the warning; typically we want to optimize the path once, then replay compiled code multiple times assume tensor shapes are roughly similar.
- ran locally, showing that this fixes some jit usage in Pyro

Support use under PyTorch jit

---

docs/source/backends.rst
opt_einsum/backends/__init__.py
opt_einsum/backends/dispatch.py
opt_einsum/backends/tensorflow.py
opt_einsum/contract.py
opt_einsum/tests/test_backends.py

This implements ``backend='auto'`` for contractions and makes it the default. This works currently by inferring the module from the class of the first array supplied. A slight detail is that sometimes the module of an array does not supply ``tensordot`` etc. (maybe it has subclassed just ``numpy.ndarray`` for example) and in this case ``'numpy'`` is still used.
Hopefully this kind of thing will eventually be made redundant by ``__array_function__`` (#46) but for the moment it makes it a bit more convenient to work with other array libraries.

Implement backend='auto' and make it the default

---

opt_einsum/__init__.py
opt_einsum/contract.py
opt_einsum/path_random.py
opt_einsum/paths.py
opt_einsum/tests/test_backends.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_paths.py

A couple of minor-ish path tweaks:
1. Factor out the ``'auto'`` path logic to an actual path function (closes #82) cc @fritzo 
2. Allow ``contract_path`` to accept shapes with the option ``shapes=True`` (rather than requiring actual array-like objects as now)
The path options and auto path choosing based on size I've implemented as dictionaries, which as well as for efficiencies sake potentially allows them to be customized in the future. E.g. users adding their own named optimizers options or setting custom 'auto' strategies.

Factor out auto path optimizer + allow shapes in contract_path

---

setup.py

This is a bug where `opt_einsum` was not correctly bound to Python 3.5+. We will need to 1) make a 3.0.1 release and 2) remove the 3.0.0 release from PyPI for this to get into full effect.
@jcmgray Please review ASAP. Happy to also patch the `optimal` path for 3.0.1 if we can get this in today.

Setup: Restricts to Python 3.5+ only

---

opt_einsum/backends/dispatch.py

Add support for [mars](https://github.com/mars-project/mars) (just needs a simple alias), a library a bit similar to `dask`.

add mars support via alias

---

docs/source/path_finding.rst
opt_einsum/__init__.py
opt_einsum/path_random.py
opt_einsum/paths.py
opt_einsum/tests/test_contract.py

Adds two ``optimize=`` presets, ``'random-greedy-128'``, and ``'auto-hq'``. These let you allow much more time for finding the path than the ``'auto'`` path targets.
``'auto-hq'`` uses:
*  ``'optimal'`` for ``n<=5``
*  ``'dp'`` for ``n<=16``
*  ``'random-greedy-128 '`` for ``n>16``
The handover from ``'dp'`` to ``'random-greedy-128 '`` works pretty smoothly in terms of timings for the random regular-like graphs. But for *planar*-like graphs, ``'dp'`` can really go 2 or 3 times bigger than 16. No sure if there is any easy way one might detect these kind of situations, but just a good point to keep in mind!
cc @mrader1248

add 'high quality' auto optimize presets

---

README.md

We seem to have hit a new level of 1.5M+ downloads/month which is quite something. I thought it might be nice to add a badge to show this off.
As a side note does anyone know which package we went into early October which caused the spike? I think the underscore in the package name is preventing GitHub from correctly finding dependencies and I am unsure how to track it through PyPI or Conda without construct the full dependency tree locally. 
At this scale it would be good to be in contact with all downstream packages like we are with Pyro.

PyPI Stats Badge

---

docs/source/api.rst
docs/source/dp_path.rst
opt_einsum/__init__.py
opt_einsum/paths.py
opt_einsum/tests/test_paths.py

These updates the ``'dp'`` optimizer in a few ways:
- fixes some edge case bugs (#116, #118) @yaroslavvb
- allows it to be customized in a few ways (without any impact on performance in the default case):
* whether to target minimum flop count or minimize size
* whether to search through outer products
* how to set the ``cost_cap`` iterate strategy (on, off or manual)
- a few tweaks to make the overhead lower for small contractions particularly
- renames ``DynamicProgrammingOptimizer->DynamicProgramming`` and add it to the top namespace
I think with these, it would make sense to make the ``'optimal'`` algorithm point at ``'dp'`` since with the outer product search it should now find all the same contractions, and with the ``cost_cap`` turned off it's as fast for small contractions as …

updates to 'dp' optimizer

---

devtools/RELEASE.md

The benefits of wheels are well documented. See: https://pythonwheels.com/
This package is pure Python and publishing it as both source and as a wheel is simple.

Publish sdist and bdist wheel

---

setup.py

PyTorch is now released for Python-3.8
Declare Python-3.8 compatible

add python 3.8

---

opt_einsum/path_random.py

Fixes random greedy optimizers for py3.5 (which doesn't have `random.choices`). Also makes the random greedy optimizer deterministic for py3.6+ (by seeding at the very beginning).
Should fix #126 (edit: doesn't address tests not running with py3.5).

fix random greedy for python 3.5 & make deterministic for 3.6+

---

devtools/travis-ci/before_install.sh
opt_einsum/backends/jax.py

We observed the following surprising behavior: importing tensorflow also imports jax, if installed. This happens because tensorflow has an opt_einsum dependency that is imported eagerly, and the opt_einsum jax backend eagerly imports jax. To avoid this, make the jax import from opt_einsum lazy.
- [ * ] Ready to go

Make JAX backend import lazy.

---

opt_einsum/backends/dispatch.py

Link the backend docs when a backend function can't be found - should help e.g. #139, to clarify that for example ``einsum`` is still required for certain pairwise contractions.

more detailed error when backend is missing a function e.g. einsum

---

opt_einsum/contract.py
opt_einsum/path_random.py
opt_einsum/paths.py
opt_einsum/tests/test_paths.py

Explicitly check that stateful path optimizers are called with the same arguments on repeat runs (should resolve #137), and error otherwise. I also updated the ``contract`` docstring with the newer ``optimize`` options, and renamed a (purely internal) variable ``dimension_dict -> size_dict`` for consistency with code elsewhere.

stateful path optimizers check args + minor doc tweaks

---

docs/source/backends.rst
opt_einsum/backends/dispatch.py
opt_einsum/backends/object_arrays.py
opt_einsum/backends/objects.py
opt_einsum/tests/test_backends.py

Add ``backend='object'`` to support contraction of arrays of arbitrary python objects (resolves #86 and #142).

support contraction of arbitrary objects

---

opt_einsum/backends/jax.py
opt_einsum/contract.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_input.py

Resolves #148, by only keeping the last 10 'remaining terms' lists in the `contraction_list`, which is generally the point it starts to look a bit messy in the `PathInfo` object. This could be tweaked / made customizable.
I've also 
* changed the 'speedup' formatting to scientific as this number can be **very** large sometimes.
* added a few more spaces inbetween the 'current' contraction and 'remaining terms' for clarity (putting them in ``[...]`` might also be clearer.
```python
>>> import opt_einsum as oe
>>> eq, shapes = oe.helpers.rand_equation(20, 3)
>>> path, info = oe.contract_path(eq, *shapes, shapes=True, optimize='greconf')
>>> info
Complete contraction:  n,aA,jhr,mw,ox,Bos,dc,Cqeu,ipDs,tBk,v,tpkD,u,fram,byqx,znfgd,eCvlbz,icg,jw,yAhl->
Naive scaling:  30
Optimized scaling:  6 …
```

contraction_list: only keep remaining for last 20 contractions

---

opt_einsum/contract.py
opt_einsum/paths.py
opt_einsum/tests/test_paths.py

This PR:
1. Fixes the bug where a too low ``memory_limit`` meant the ``'dp'`` optimizer would search forever (#153)
2. Puts ``tensordot`` axes in a canonical order (the order they appear on the first operand), so that performance shouldn't change unexpectedly (#143)
3. Changes an ``isinstance`` call to ``infer_backend`` (is cleaner? and fixes a rare bug when mixing inputs for e.g. jax compiled contraction)

Small fixes: 'dp' and memory_limit + tensordot axes order

---

.github/workflows/Linting.yml
devtools/conda-envs/full-environment.yaml
devtools/conda-envs/min-deps-environment.yaml
devtools/conda-envs/min-ver-environment.yaml
opt_einsum/__init__.py
opt_einsum/backends/__init__.py
opt_einsum/backends/dispatch.py
opt_einsum/backends/object_arrays.py
opt_einsum/blas.py
opt_einsum/contract.py
opt_einsum/helpers.py
opt_einsum/parser.py
opt_einsum/path_random.py
opt_einsum/paths.py
opt_einsum/sharing.py
opt_einsum/tests/test_backends.py
opt_einsum/tests/test_sharing.py
opt_einsum/typing.py
setup.cfg
setup.py

Bumps minimum python version to 3.6 according to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). We should bump to 3.7, but many libraries (torch!) are relatively slow to deprecate python versions, this seems like a reasonable compromise which allows us to type the library.
Notable points that this PR has either accomplished or will accomplish.

Python Type Annotations

---

.github/workflows/Tests.yml
opt_einsum/paths.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_paths.py

The dynamic path will find disconnected subgraphs such as `aa, bc->bc` and automatically contract `aa->` on the fly as a pre optimization measure; however, the contraction `,bc->bc` (float, matrix -> matrix) was not considered and the float is first pre contracted `->` (a no-op). This PR prevents these no-ops to simplify the output path.

Prevents double contraction of floats in dynamic path, fixes #172

---

docs/paths/dp_path.md
opt_einsum/paths.py
opt_einsum/tests/test_paths.py

This adds more custom functions to the dp solver as outlined in #171. For example:
```python
opt = oe.DynamicProgramming(minimize='combo')
```
should give better real world performance in many cases than the pure minimized flop cost alone.
Also included is a couple of 'micro' optimizations  for the path finders performance - namely, making some inner loop calls functions not methods.

more custom dp scores for faster contractions

---

setup.py

Fully qualify license trove classifier. This allows tools such as `pip-licenses` to generate a nice license report and matches how other packages in the ecosystem publish their license.

Fully qualify license trove classifier

---

opt_einsum/contract.py
opt_einsum/tests/test_backends.py

Allows `backend=None`, which should be fairly unambiguous, as an alternative to 'auto', closes #193.

allow backend=None

---

opt_einsum/contract.py
opt_einsum/parser.py
opt_einsum/paths.py
opt_einsum/tests/test_parser.py

This PR adds support for the shapes kwarg for `parse_einsum_input`. This also fixes a bug where `contract_path` takes in the shapes parameter but `parse_einsum_input` is called without respecting the shapes parameter.
The bug results because even though the user had input shapes as True, `contract_path` will call `parse_einsum_input` _before_ caring about shapes, and within `parse_einsum_input`, will call .shape on an array that is already a shape.
Notable points that this PR has either accomplished or will accomplish.

[BUG FIX] Add shapes support to parse_einsum_input

---

versioneer.py

The SafeConfigParser class will be renamed to ConfigParser in Python 3.12 [1]. This alias will be removed in future versions.So we can use ConfigParser directly instead.
[1] https://github.com/python/cpython/issues/89336
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Provide a brief description of the PR's purpose here.
Notable points that this PR has either accomplished or will accomplish.

Use ConfigParser instead of SafeConfigParser

---

docs/getting_started/backends.md

deduplicate backends.md

---

opt_einsum/parser.py
opt_einsum/tests/test_input.py

```python
contract("ij->jij", [[0, 0], [0, 0]])
```
currently relies on the backend to throw an error if an output subscript is specified multiple times. However
```python
contract_path("ij->jij", [[0, 0], [0, 0]])
```
would still return an einsum path despite the wrong einsum equation. This might lead to subtle errors if a user ends up relying on this behaviour by accident. E.g. when using the jax backend no error is thrown but only an internal assertion fails.
This PR raises the error already in `parse_einsum_input` which ensures that `contract_path` matches the behaviour of `np.einsum` and all backends that might rely on `opt_einsum` for error handling will do so as well.
This PR also extends the unittests to test error handling for both `contract_path` and `contract` which is …

Raise error in `parse_einsum_input` when output subscript is specified multiple times

---

opt_einsum/contract.py
opt_einsum/tests/test_edge_cases.py

This simply handles the case when `PathInfo` is constructed with an empty path (e.g. for the no-op contraction `eq="->"`) with some defaults rather than raising `ZeroDivisionError`. See https://github.com/jcmgray/quimb/issues/231.

handle empty contraction list in PathInfo

---

devtools/conda-envs/full-environment.yaml
devtools/conda-envs/min-deps-environment.yaml
devtools/conda-envs/min-ver-environment.yaml
devtools/conda-envs/torch-only-environment.yaml
docs/changelog.md
opt_einsum/contract.py
opt_einsum/paths.py
opt_einsum/tests/test_contract.py
opt_einsum/tests/test_input.py
opt_einsum/tests/test_paths.py

This makes the final tweaks and change log notes for the upcoming v3.4.0 release.
CC @janeyx99

v3.4 Release notes and removes NumPy kwargs

---

.github/workflows/Linting.yml
Makefile
opt_einsum/contract.py
opt_einsum/testing.py
opt_einsum/tests/test_input.py

Fixes #245 due to a tuple return rather than a mutable list when shapes are prepared.
Notable points that this PR has either accomplished or will accomplish.

Interleaved contract_path shapes fix 

---

docs/requirements.yml
mkdocs.yml

The previous approach to passing options to `mkdocstrings-python` started showing deprecation warnings with `mkdocstrings` 0.28.0, and started failing with `mkdocstrings` 0.28.3.

Fix documentation build with mkdocstrings 0.29
